# Generated by Django 4.2.14 on 2025-09-15 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('email_change', 'Email Change'), ('account_deactivation', 'Account Deactivation'), ('account_reactivation', 'Account Reactivation'), ('settings_update', 'Settings Update'), ('privacy_update', 'Privacy Settings Update'), ('notification_update', 'Notification Settings Update'), ('search', 'Search Activity'), ('navigation', 'Page Navigation'), ('error', 'Error Encountered'), ('feature_usage', 'Feature Usage')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activity',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='user_activi_user_id_3b1b11_idx'), models.Index(fields=['activity_type', 'timestamp'], name='user_activi_activit_25fc27_idx'), models.Index(fields=['user', 'activity_type'], name='user_activi_user_id_f188ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('interaction_type', models.CharField(choices=[('connection_request', 'Connection Request'), ('connection_accept', 'Connection Accept'), ('connection_decline', 'Connection Decline'), ('connection_remove', 'Connection Remove'), ('message_send', 'Message Send'), ('message_read', 'Message Read'), ('group_join', 'Group Join'), ('group_leave', 'Group Leave'), ('group_invite', 'Group Invite'), ('mention', 'Mention'), ('tag', 'Tag'), ('recommendation_view', 'Recommendation View'), ('recommendation_dismiss', 'Recommendation Dismiss')], max_length=25)),
                ('context_type', models.CharField(blank=True, max_length=50, null=True)),
                ('context_id', models.CharField(blank=True, max_length=100, null=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_interactions_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Interaction',
                'verbose_name_plural': 'Social Interactions',
                'db_table': 'social_interaction',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='social_inte_user_id_dc4563_idx'), models.Index(fields=['target_user', 'timestamp'], name='social_inte_target__693913_idx'), models.Index(fields=['interaction_type', 'timestamp'], name='social_inte_interac_3e4cfb_idx'), models.Index(fields=['user', 'target_user'], name='social_inte_user_id_59bbd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('web', 'Web Session'), ('mobile', 'Mobile Session'), ('api', 'API Session'), ('admin', 'Admin Session')], default='web', max_length=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('pages_visited', models.PositiveIntegerField(default=0)),
                ('actions_performed', models.PositiveIntegerField(default=0)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('location_data', models.JSONField(blank=True, default=dict)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('exit_page', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Activity',
                'verbose_name_plural': 'Session Activities',
                'db_table': 'session_activity',
                'indexes': [models.Index(fields=['user', 'start_time'], name='session_act_user_id_4baaf1_idx'), models.Index(fields=['session_id'], name='session_act_session_159728_idx'), models.Index(fields=['session_type', 'start_time'], name='session_act_session_887d9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('activity_type', models.CharField(choices=[('profile_view', 'Profile View'), ('profile_follow', 'Profile Follow'), ('profile_unfollow', 'Profile Unfollow'), ('profile_block', 'Profile Block'), ('profile_unblock', 'Profile Unblock'), ('profile_report', 'Profile Report'), ('profile_message', 'Profile Message'), ('profile_share', 'Profile Share'), ('achievement_view', 'Achievement View'), ('experience_view', 'Experience View'), ('posts_browse', 'Posts Browse'), ('stories_browse', 'Stories Browse')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Activity',
                'verbose_name_plural': 'Profile Activities',
                'db_table': 'profile_activity',
                'indexes': [models.Index(fields=['visitor', 'timestamp'], name='profile_act_visitor_7e6a04_idx'), models.Index(fields=['profile_owner', 'timestamp'], name='profile_act_profile_735f7e_idx'), models.Index(fields=['activity_type', 'timestamp'], name='profile_act_activit_89100e_idx'), models.Index(fields=['visitor', 'profile_owner'], name='profile_act_visitor_57c8ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('gif', 'GIF'), ('thumbnail', 'Thumbnail')], max_length=20)),
                ('media_id', models.CharField(max_length=100)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('interaction_type', models.CharField(choices=[('click', 'Click'), ('view', 'View'), ('download', 'Download'), ('share', 'Share'), ('zoom', 'Zoom'), ('play', 'Play'), ('pause', 'Pause'), ('seek', 'Seek'), ('fullscreen', 'Fullscreen'), ('volume_change', 'Volume Change'), ('quality_change', 'Quality Change')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('position_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Interaction',
                'verbose_name_plural': 'Media Interactions',
                'db_table': 'media_interaction',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='media_inter_user_id_f0dda0_idx'), models.Index(fields=['media_type', 'media_id'], name='media_inter_media_t_46d148_idx'), models.Index(fields=['interaction_type', 'timestamp'], name='media_inter_interac_15095d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('story', 'Story'), ('comment', 'Comment'), ('community_post', 'Community Post'), ('review', 'Review')], max_length=20)),
                ('content_id', models.CharField(max_length=100)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('unlike', 'Unlike'), ('comment', 'Comment'), ('share', 'Share'), ('save', 'Save'), ('unsave', 'Unsave'), ('pin', 'Pin'), ('unpin', 'Unpin'), ('report', 'Report'), ('hide', 'Hide'), ('react', 'React'), ('unreact', 'Unreact'), ('rate', 'Rate'), ('scroll_depth', 'Scroll Depth'), ('time_spent', 'Time Spent')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('scroll_depth_percentage', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Interaction',
                'verbose_name_plural': 'Content Interactions',
                'db_table': 'content_interaction',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='content_int_user_id_2d4c18_idx'), models.Index(fields=['content_type', 'content_id'], name='content_int_content_0ad376_idx'), models.Index(fields=['interaction_type', 'timestamp'], name='content_int_interac_dabef8_idx'), models.Index(fields=['user', 'content_type', 'interaction_type'], name='content_int_user_id_6efb08_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('date', models.DateField()),
                ('activity_counts', models.JSONField(default=dict)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_aggregations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Aggregation',
                'verbose_name_plural': 'Activity Aggregations',
                'db_table': 'activity_aggregation',
                'indexes': [models.Index(fields=['user', 'date'], name='activity_ag_user_id_8b6772_idx'), models.Index(fields=['aggregation_type', 'date'], name='activity_ag_aggrega_72fffa_idx')],
                'unique_together': {('user', 'aggregation_type', 'date')},
            },
        ),
    ]
