# Generated by Django 4.2.14 on 2025-09-15 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VibeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('activity_type', models.CharField(choices=[('vibe_create', 'Vibe Create'), ('vibe_send', 'Vibe Send'), ('vibe_receive', 'Vibe Receive'), ('vibe_view', 'Vibe View'), ('vibe_search', 'Vibe Search'), ('vibe_category_browse', 'Vibe Category Browse'), ('vibe_popularity_view', 'Vibe Popularity View'), ('vibe_score_update', 'Vibe Score Update')], max_length=25)),
                ('vibe_type', models.CharField(choices=[('individual', 'Individual Vibe'), ('community', 'Community Vibe'), ('brand', 'Brand Vibe'), ('service', 'Service Vibe'), ('main', 'Main Vibe')], max_length=15)),
                ('vibe_id', models.CharField(max_length=100)),
                ('vibe_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vibe_category', models.CharField(blank=True, max_length=100, null=True)),
                ('target_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vibe_score', models.FloatField(blank=True, null=True)),
                ('iq_impact', models.FloatField(blank=True, null=True)),
                ('aq_impact', models.FloatField(blank=True, null=True)),
                ('sq_impact', models.FloatField(blank=True, null=True)),
                ('hq_impact', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibe_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vibe Activity',
                'verbose_name_plural': 'Vibe Activities',
                'db_table': 'vibe_activity',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='vibe_activi_user_id_35b763_idx'), models.Index(fields=['activity_type', 'timestamp'], name='vibe_activi_activit_90577b_idx'), models.Index(fields=['vibe_type', 'timestamp'], name='vibe_activi_vibe_ty_4ef7ea_idx'), models.Index(fields=['user', 'activity_type'], name='vibe_activi_user_id_f627cb_idx'), models.Index(fields=['vibe_id', 'activity_type'], name='vibe_activi_vibe_id_b492a7_idx'), models.Index(fields=['target_user_id', 'timestamp'], name='vibe_activi_target__6a555d_idx')],
            },
        ),
    ]
