# Generated by Django 4.2.14 on 2025-09-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0002_vibeactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('connection_request', 'Connection Request'), ('connection_accept', 'Connection Accept'), ('connection_decline', 'Connection Decline'), ('connection_remove', 'Connection Remove'), ('message_send', 'Message Send'), ('message_read', 'Message Read'), ('group_join', 'Group Join'), ('group_leave', 'Group Leave'), ('group_invite', 'Group Invite'), ('mention', 'Mention'), ('tag', 'Tag'), ('recommendation_view', 'Recommendation View'), ('recommendation_dismiss', 'Recommendation Dismiss'), ('profile_visit', 'Profile Visit')], max_length=25),
        ),
    ]
