# Generated by Django 4.2.14 on 2025-10-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0003_alter_socialinteraction_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentinteraction',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('story', 'Story'), ('comment', 'Comment'), ('community_post', 'Community Post'), ('review', 'Review'), ('connection', 'Connection'), ('conversation_message', 'Conversation Message'), ('matrix_message', 'Matrix Message')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contentinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('unlike', 'Unlike'), ('comment', 'Comment'), ('share', 'Share'), ('save', 'Save'), ('unsave', 'Unsave'), ('pin', 'Pin'), ('unpin', 'Unpin'), ('report', 'Report'), ('hide', 'Hide'), ('react', 'React'), ('unreact', 'Unreact'), ('rate', 'Rate'), ('scroll_depth', 'Scroll Depth'), ('time_spent', 'Time Spent'), ('create', 'Create')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mediainteraction',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('gif', 'GIF'), ('thumbnail', 'Thumbnail'), ('comment_media', 'Comment Media')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('email_change', 'Email Change'), ('account_deactivation', 'Account Deactivation'), ('account_reactivation', 'Account Reactivation'), ('settings_update', 'Settings Update'), ('privacy_update', 'Privacy Settings Update'), ('notification_update', 'Notification Settings Update'), ('search', 'Search Activity'), ('navigation', 'Page Navigation'), ('error', 'Error Encountered'), ('feature_usage', 'Feature Usage'), ('post_create', 'Post Created'), ('post_update', 'Post Updated'), ('story_create', 'Story Created'), ('community_create', 'Community Created'), ('page_view', 'Page View'), ('session_data', 'Session Data'), ('scroll', 'Scroll Activity')], max_length=50),
        ),
    ]
