# Generated by Django 4.2.0 on 2024-01-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrustCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('trust_score', models.FloatField(default=2.0)),
                ('trust_rank', models.CharField(default='bronze', max_length=20)),
                ('trust_percentile', models.FloatField(default=50.0)),
                ('content_quality_score', models.FloatField(default=2.0)),
                ('engagement_authenticity', models.FloatField(default=2.0)),
                ('violation_risk_score', models.FloatField(default=0.0)),
                ('moderation_status', models.CharField(default='active', max_length=20)),
                ('violation_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cache_version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'truststream_user_cache',
            },
        ),
        migrations.CreateModel(
            name='ContentModerationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.CharField(max_length=255)),
                ('moderation_status', models.CharField(max_length=20)),
                ('moderation_confidence', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('content_trust_score', models.FloatField(default=2.0)),
                ('safety_score', models.FloatField(default=2.0)),
                ('authenticity_score', models.FloatField(default=2.0)),
                ('violation_types', models.JSONField(default=list)),
                ('analyzing_agents', models.JSONField(default=list)),
                ('consensus_score', models.FloatField(default=0.0)),
                ('moderated_at', models.DateTimeField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('cache_version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'truststream_content_cache',
            },
        ),
        migrations.CreateModel(
            name='CommunityHealthCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('community_health_score', models.FloatField(default=2.0)),
                ('content_quality_avg', models.FloatField(default=2.0)),
                ('member_trust_avg', models.FloatField(default=2.0)),
                ('engagement_authenticity', models.FloatField(default=2.0)),
                ('violation_rate', models.FloatField(default=0.0)),
                ('toxicity_score', models.FloatField(default=0.0)),
                ('safety_rating', models.CharField(default='safe', max_length=20)),
                ('total_moderations', models.IntegerField(default=0)),
                ('auto_approvals', models.IntegerField(default=0)),
                ('human_reviews', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cache_version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'truststream_community_cache',
            },
        ),
        migrations.CreateModel(
            name='TrustScoreCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=255)),
                ('trust_score', models.FloatField()),
                ('trust_rank', models.CharField(max_length=20)),
                ('score_breakdown', models.JSONField()),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('calculation_version', models.CharField(max_length=20)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'truststream_score_cache',
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=50)),
                ('decision', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('reasoning', models.TextField()),
                ('analyzing_agents', models.JSONField()),
                ('human_reviewed', models.BooleanField(default=False)),
                ('appealed', models.BooleanField(default=False)),
                ('appeal_outcome', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'truststream_moderation_log',
            },
        ),
        migrations.CreateModel(
            name='AgentPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_version', models.CharField(max_length=20)),
                ('total_analyses', models.IntegerField(default=0)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('false_positives', models.IntegerField(default=0)),
                ('false_negatives', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('precision_rate', models.FloatField(default=0.0)),
                ('recall_rate', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('performance_trend', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'truststream_agent_metrics',
            },
        ),
        migrations.CreateModel(
            name='TrustNetworkAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.CharField(max_length=255)),
                ('analysis_date', models.DateField()),
                ('total_nodes', models.IntegerField()),
                ('total_edges', models.IntegerField()),
                ('network_density', models.FloatField()),
                ('clustering_coefficient', models.FloatField()),
                ('average_path_length', models.FloatField()),
                ('trust_distribution', models.JSONField()),
                ('influential_users', models.JSONField()),
                ('trust_clusters', models.JSONField()),
                ('anomaly_scores', models.JSONField()),
                ('network_health_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'truststream_network_analytics',
            },
        ),
        migrations.AddIndex(
            model_name='usertrustcache',
            index=models.Index(fields=['trust_score'], name='truststream_user_cache_trust_score_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrustcache',
            index=models.Index(fields=['trust_rank'], name='truststream_user_cache_trust_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrustcache',
            index=models.Index(fields=['moderation_status'], name='truststream_user_cache_moderation_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trustscoreCache',
            index=models.Index(fields=['entity_type', 'entity_id'], name='truststream_score_cache_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='trustscoreCache',
            index=models.Index(fields=['expires_at'], name='truststream_score_cache_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='trustnetworkanalytics',
            index=models.Index(fields=['community_id'], name='truststream_network_analytics_community_id_idx'),
        ),
        migrations.AddIndex(
            model_name='trustnetworkanalytics',
            index=models.Index(fields=['analysis_date'], name='truststream_network_analytics_analysis_date_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['content_type', 'content_id'], name='truststream_moderation_log_content_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['user_id'], name='truststream_moderation_log_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['created_at'], name='truststream_moderation_log_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='contentmoderationcache',
            index=models.Index(fields=['moderation_status'], name='truststream_content_cache_moderation_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contentmoderationcache',
            index=models.Index(fields=['risk_level'], name='truststream_content_cache_risk_level_idx'),
        ),
        migrations.AddIndex(
            model_name='contentmoderationcache',
            index=models.Index(fields=['content_trust_score'], name='truststream_content_cache_content_trust_score_idx'),
        ),
        migrations.AddIndex(
            model_name='communityhealthcache',
            index=models.Index(fields=['community_health_score'], name='truststream_community_cache_community_health_score_idx'),
        ),
        migrations.AddIndex(
            model_name='communityhealthcache',
            index=models.Index(fields=['safety_rating'], name='truststream_community_cache_safety_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='communityhealthcache',
            index=models.Index(fields=['violation_rate'], name='truststream_community_cache_violation_rate_idx'),
        ),
        migrations.AddIndex(
            model_name='agentperformancemetrics',
            index=models.Index(fields=['agent_name'], name='truststream_agent_metrics_agent_name_idx'),
        ),
        migrations.AddIndex(
            model_name='agentperformancemetrics',
            index=models.Index(fields=['accuracy_rate'], name='truststream_agent_metrics_accuracy_rate_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trustscoreCache',
            unique_together={('entity_type', 'entity_id')},
        ),
        migrations.AlterUniqueTogether(
            name='trustnetworkanalytics',
            unique_together={('community_id', 'analysis_date')},
        ),
        migrations.AlterUniqueTogether(
            name='contentmoderationcache',
            unique_together={('content_type', 'content_id')},
        ),
        migrations.AlterUniqueTogether(
            name='agentperformancemetrics',
            unique_together={('agent_name', 'agent_version')},
        ),
    ]