# Generated by Django 4.2.14 on 2024-08-16 10:07

import auth_manager.enums.otp_purpose_enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0002_otp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('forget_password', 'FORGET_PASSWORD'), ('email_verification', 'EMAIL_VERIFICATION'), ('other', 'OTHER')], default=auth_manager.enums.otp_purpose_enum.OtpPurposeEnum['EMAIL_VERIFICATION'], max_length=255),
        ),
    ]
