# Generated by Django 4.2.14 on 2024-08-30 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0003_alter_otp_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeScreenMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='welcomescreenimages/')),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('content_type', models.CharField(choices=[('brand', 'Brand'), ('personal', 'Personal Account')], default='personal', max_length=10)),
            ],
            options={
                'verbose_name': 'Welcome Screen Message',
                'verbose_name_plural': 'Welcome Screen Messages',
                'ordering': ['rank', '-timestamp'],
            },
        ),
    ]
