# Generated by Django 4.2.14 on 2024-09-23 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_manager', '0004_welcomescreenmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.JSONField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Contact',
                'verbose_name_plural': 'Upload Contact',
                'ordering': ['-created_on'],
            },
        ),
    ]
