# Generated by Django 4.2.14 on 2024-10-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0006_profilereactionmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sub_interests', models.JSONField(default=list)),
            ],
        ),
    ]
