# Generated by Django 4.2.14 on 2024-12-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0007_interestlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackProfileReactionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('profile_vibe', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Profile Reaction Manager',
                'verbose_name_plural': 'Profile Reaction Managers',
            },
        ),
    ]
