# Generated by Django 4.2.14 on 2025-02-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0009_country_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Country Information',
                'verbose_name_plural': 'Countries Information',
            },
        ),
        migrations.CreateModel(
            name='StateInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='auth_manager.countryinfo')),
            ],
            options={
                'verbose_name': 'State Information',
                'verbose_name_plural': 'States Information',
            },
        ),
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255, unique=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='auth_manager.stateinfo')),
            ],
            options={
                'verbose_name': 'City Information',
                'verbose_name_plural': 'Cities Information',
            },
        ),
    ]
