# Generated by Django 4.2.14 on 2025-02-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0010_countryinfo_stateinfo_cityinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='city_name',
            field=models.CharField(max_length=255),
        ),
    ]
