# Generated by Django 4.2.14 on 2025-03-20 10:23

import auth_manager.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_manager', '0011_alter_cityinfo_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_token', models.CharField(default=auth_manager.models.generate_hashed_uuid, editable=False, max_length=64, unique=True)),
                ('origin_type', models.CharField(choices=[('menu', 'Menu'), ('community', 'Community'), ('truth_section', 'Truth Section')], max_length=20)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(default=auth_manager.models.default_expiry_date)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('login_users', models.ManyToManyField(blank=True, related_name='used_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invite',
                'verbose_name_plural': 'Invites',
                'ordering': ['-creation_date'],
            },
        ),
    ]
