# Generated by Django 4.2.14 on 2025-03-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0012_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDataReactionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('education_vibe', models.JSONField(default=list)),
                ('achievement_vibe', models.JSONField(default=list)),
                ('skill_vibe', models.JSONField(default=list)),
                ('experience_vibe', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Profile Data Reaction Manager',
                'verbose_name_plural': 'Profile Data Reaction Managers',
            },
        ),
    ]
