# Generated by Django 4.2.14 on 2025-03-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0013_profiledatareactionmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementReactionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('achievement_vibe', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Achievement Reaction Manager',
                'verbose_name_plural': 'Achievement Reaction Managers',
            },
        ),
    ]
