# Generated by Django 4.2.14 on 2025-03-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0014_achievementreactionmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationReactionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('education_vibe', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Education Reaction Manager',
                'verbose_name_plural': 'Education Reaction Managers',
            },
        ),
        migrations.CreateModel(
            name='ExperienceReactionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('experience_vibe', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Experience Reaction Manager',
                'verbose_name_plural': 'Experience Reaction Managers',
            },
        ),
        migrations.CreateModel(
            name='SkillReactionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('skill_vibe', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Skill Reaction Manager',
                'verbose_name_plural': 'Skill Reaction Managers',
            },
        ),
    ]
