# Generated by Django - Initial migration for notification app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(db_index=True, help_text='User UID from Neo4j', max_length=255)),
                ('notification_type', models.CharField(db_index=True, help_text='Type of notification', max_length=100)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('body', models.TextField(help_text='Notification body/message')),
                ('device_id', models.CharField(help_text='FCM device token', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(default='normal', help_text='Notification priority', max_length=20)),
                ('click_action', models.CharField(blank=True, help_text='Deep link action', max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Image URL for rich notification', null=True)),
                ('data', models.JSONField(default=dict, help_text='Additional notification data')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether notification was read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(db_index=True, help_text='Type of notification sent', max_length=100)),
                ('recipient_count', models.IntegerField(default=0, help_text='Number of recipients')),
                ('successful_count', models.IntegerField(default=0, help_text='Number of successful sends')),
                ('failed_count', models.IntegerField(default=0, help_text='Number of failed sends')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('metadata', models.JSONField(default=dict, help_text='Additional notification metadata')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(db_index=True, help_text='Type of notification', max_length=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this notification type is enabled for the user')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['-created_at', 'user_uid'], name='notificatio_created_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user_uid', 'is_read'], name='notificatio_user_ui_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['notification_type', 'status'], name='notificatio_notific_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['status'], name='notificatio_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['-created_at', 'notification_type'], name='notificatio_created_log_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='notificatio_status_log_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['is_enabled'], name='notificatio_is_enab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'notification_type')},
        ),
    ]


