# Generated by Django 4.2.14 on 2025-11-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_created_8b707a_idx',
            old_name='notificatio_created_log_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_status_ff05ed_idx',
            old_name='notificatio_status_log_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='notificatio_user_id_9944d0_idx',
            old_name='notificatio_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='notificatio_is_enab_6ad736_idx',
            old_name='notificatio_is_enab_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='notificatio_created_e9fe90_idx',
            old_name='notificatio_created_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='notificatio_user_ui_02a557_idx',
            old_name='notificatio_user_ui_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='notificatio_notific_69b4ba_idx',
            old_name='notificatio_notific_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='notificatio_status_538e1d_idx',
            old_name='notificatio_status_idx',
        ),
    ]
