# Generated by Django 4.2.14 on 2024-10-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityReactionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('community_vibe', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Community Reaction Manager',
                'verbose_name_plural': 'Community Reaction Managers',
            },
        ),
    ]
