# Generated by Django 4.2.14 on 2024-10-23 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communityreactionmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCommunityUserManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_uid', models.CharField(max_length=255, unique=True)),
                ('community_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_ids', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Generated Community User Manager',
                'verbose_name_plural': 'Generated Community User Managers',
                'ordering': ['-created_on'],
            },
        ),
    ]
