# Generated by Django 4.2.14 on 2024-11-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryReactionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('story_vibe', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Story Reaction Manager',
                'verbose_name_plural': 'Story Reaction Managers',
            },
        ),
    ]
