# Generated by Django 4.2.14 on 2024-08-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadfiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
