# Generated by Django 4.2.14 on 2024-09-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_delete_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(upload_to='feeds/'),
        ),
    ]
