# Generated by Django 4.2.14 on 2024-09-10 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('user', 'User'), ('community', 'Community'), ('other', 'Other')], default='other', help_text='Select the type of report. This helps categorize the report.', max_length=20, verbose_name='Report Type')),
                ('reported_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the object being reported. This can be used to reference the specific object. Leave blank if not applicable.', null=True, verbose_name='Reported Object ID')),
                ('reported_object_type', models.CharField(blank=True, help_text='Type of the object being reported (e.g., "Post", "Comment"). This helps in identifying the type of object. Leave blank if not applicable.', max_length=50, verbose_name='Reported Object Type')),
                ('description', models.TextField(help_text='Detailed description of the report. Provide as much detail as possible.', verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', help_text='Current status of the report. Indicates the progress of handling the report.', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the report was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the report was last updated.', verbose_name='Updated At')),
                ('reported_by', models.ForeignKey(blank=True, help_text='The user who made the report. Leave blank if the report is anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Reported By')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
