# Generated by Django 4.2.14 on 2024-09-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_object_type',
            field=models.CharField(blank=True, help_text='Type of the object being reported (e.g., "Post", "Comment"). This helps in identifying the type of object. Leave blank if not applicable.', max_length=50, null=True, verbose_name='Reported Object Type'),
        ),
    ]
