# Generated by Django 4.2.14 on 2024-09-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_report_reported_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional information about the report, e.g., Post ID, Post object in string format.', null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('user', 'User'), ('community', 'Community'), ('other', 'Other'), ('post', 'Post')], default='other', help_text='Select the type of report. This helps categorize the report.', max_length=20, verbose_name='Report Type'),
        ),
    ]
