# Generated by Django 4.2.14 on 2024-09-19 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0003_report_notes_alter_report_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version number of the privacy policy', max_length=20, unique=True)),
                ('content', models.TextField(help_text='Full text of the privacy policy')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this version of the policy is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
                'db_table': 'privacy_policy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional information about the report, e.g., Post ID, Post object in string format.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('user', 'USER'), ('community', 'COMMUNITY'), ('other', 'OTHER'), ('post', 'POST'), ('profile', 'PROFILE')], default='other', help_text='Select the type of report. This helps categorize the report.', max_length=20, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('in_progress', 'IN_PROGRESS'), ('resolved', 'RESOLVED'), ('closed', 'CLOSED')], default='pending', help_text='Current status of the report. Indicates the progress of handling the report.', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='AcceptPrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the policy was accepted')),
                ('privacy_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_users', to='monitoring.privacypolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_privacy_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accepted Privacy Policy',
                'verbose_name_plural': 'Accepted Privacy Policies',
                'db_table': 'accept_privacy_policy',
                'ordering': ['-accepted_at'],
                'unique_together': {('user', 'privacy_policy')},
            },
        ),
    ]
