# Generated by Django 4.2.14 on 2024-09-09 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The main relation type, e.g., Relatives, Friend, Professional.', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_relation_name', models.CharField(help_text='Specific sub-relation, e.g., father, son, husband.', max_length=100)),
                ('directionality', models.CharField(choices=[('Unidirectional', 'Unidirectional'), ('Bidirectional', 'Bidirectional')], help_text='The direction of the relationship.', max_length=50)),
                ('approval_required', models.BooleanField(default=True, help_text='Is approval required for this relationship?')),
                ('reverse_connection', models.CharField(blank=True, help_text='The reverse relation of this sub-relation, e.g., for Father -> Child.', max_length=100)),
                ('relation', models.ForeignKey(help_text='The main relation type this sub-relation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_relations', to='connection.relation')),
            ],
            options={
                'unique_together': {('relation', 'sub_relation_name')},
            },
        ),
    ]
