# Generated by Django 4.2.14 on 2025-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrelation',
            name='default_circle',
            field=models.CharField(blank=True, help_text='The default circle for this sub-relation', max_length=100),
        ),
    ]
