# Generated by Django 4.2.14 on 2025-08-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentic', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentactionlog',
            new_name='agentic_age_agent_u_9c720b_idx',
            old_name='agentic_age_agent_u_b8e5a4_idx',
        ),
        migrations.RenameIndex(
            model_name='agentactionlog',
            new_name='agentic_age_communi_6d6a2c_idx',
            old_name='agentic_age_communi_4c8b9a_idx',
        ),
        migrations.RenameIndex(
            model_name='agentactionlog',
            new_name='agentic_age_action__4ff17a_idx',
            old_name='agentic_age_action__7f2c1d_idx',
        ),
        migrations.RenameIndex(
            model_name='agentactionlog',
            new_name='agentic_age_success_e536f5_idx',
            old_name='agentic_age_success_8a9e2f_idx',
        ),
        migrations.RenameIndex(
            model_name='agentmemory',
            new_name='agentic_age_agent_u_ddbdf6_idx',
            old_name='agentic_age_agent_u_c5d7e8_idx',
        ),
        migrations.RenameIndex(
            model_name='agentmemory',
            new_name='agentic_age_memory__e606be_idx',
            old_name='agentic_age_memory__9f3a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='agentmemory',
            new_name='agentic_age_expires_d0d186_idx',
            old_name='agentic_age_expires_2e4b6c_idx',
        ),
    ]
