# Generated by Django 4.2.14 on 2024-10-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_vibe', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('weightage_bqq', models.IntegerField()),
                ('weightage_brq', models.IntegerField()),
                ('weightage_biq', models.IntegerField()),
                ('weightage_bsq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunityVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_vibe', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('weightage_ceq', models.IntegerField()),
                ('weightage_csq', models.IntegerField()),
                ('weightage_cgq', models.IntegerField()),
                ('weightage_ciq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_vibe', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('weightage_iaq', models.IntegerField()),
                ('weightage_iiq', models.IntegerField()),
                ('weightage_ihq', models.IntegerField()),
                ('weightage_isq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_vibe', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('weightage_seq', models.IntegerField()),
                ('weightage_srq', models.IntegerField()),
                ('weightage_ssq', models.IntegerField()),
                ('weightage_suq', models.IntegerField()),
            ],
        ),
    ]
